<?php

use Illuminate\Database\Seeder;
use App\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*Carta delixius*/
        Product::create(['name'=>'Camarones ap con queso','description'=>'','price'=>4800,'producttype_id'=>1]);
        Product::create(['name'=>'Camarones apanados','description'=>'','price'=>4500,'producttype_id'=>1]);
        Product::create(['name'=>'Chorrillana','description'=>'','price'=>5500,'producttype_id'=>1]);
        Product::create(['name'=>'Gyosas champiñon queso','description'=>'','price'=>3200,'producttype_id'=>1]);
        Product::create(['name'=>'Gyosas de champiñon','description'=>'','price'=>3500,'producttype_id'=>1]);
        Product::create(['name'=>'Gyosas de cerdo','description'=>'','price'=>3200,'producttype_id'=>1]);
        Product::create(['name'=>'Gyosas de pollo','description'=>'','price'=>3200,'producttype_id'=>1]);
        Product::create(['name'=>'Hosomaqui','description'=>'','price'=>3500,'producttype_id'=>1]);
        Product::create(['name'=>'Leche de tigre','description'=>'','price'=>6000,'producttype_id'=>1]);
        Product::create(['name'=>'Papas fritas','description'=>'','price'=>2500,'producttype_id'=>1]);
        Product::create(['name'=>'Papas queso chedar','description'=>'','price'=>2500,'producttype_id'=>1]);
        Product::create(['name'=>'Sashimi tako','description'=>'','price'=>4500,'producttype_id'=>1]);
        Product::create(['name'=>'Sashimi sake','description'=>'','price'=>4800,'producttype_id'=>1]);
        Product::create(['name'=>'Tory balls','description'=>'','price'=>4800,'producttype_id'=>1]);
        Product::create(['name'=>'Yoki torys','description'=>'','price'=>3700,'producttype_id'=>1]);
        Product::create(['name'=>'Cali salu (sesamo)','description'=>'','price'=>4500,'producttype_id'=>2]);
        Product::create(['name'=>'Avocado esp (sesamo)','description'=>'','price'=>4500,'producttype_id'=>2]);
        Product::create(['name'=>'Spicy tempu (sesamo)','description'=>'','price'=>4800,'producttype_id'=>2]);
        Product::create(['name'=>'Spicy tako (sesamo)','description'=>'','price'=>5000,'producttype_id'=>2]);
        Product::create(['name'=>'Beef rolls (sesamo)','description'=>'','price'=>5000,'producttype_id'=>2]);
        Product::create(['name'=>'Maguro rolls (sesamo)','description'=>'','price'=>4500,'producttype_id'=>2]);
        Product::create(['name'=>'Temp chees (sesamo)','description'=>'','price'=>4500,'producttype_id'=>2]);
        Product::create(['name'=>'Tory rolls (sesamo)','description'=>'','price'=>4200,'producttype_id'=>2]);
        Product::create(['name'=>'Maki tolls (sesamo)','description'=>'','price'=>4000,'producttype_id'=>2]);
        Product::create(['name'=>'Tako rolls (sesamo)','description'=>'','price'=>4500,'producttype_id'=>2]);
        Product::create(['name'=>'Crab chees (sesamo)','description'=>'','price'=>5000,'producttype_id'=>2]);
        Product::create(['name'=>'Teri chees','description'=>'','price'=>4000,'producttype_id'=>2]);
        Product::create(['name'=>'EBI rolls (sesamo)','description'=>'','price'=>4500,'producttype_id'=>2]);
        Product::create(['name'=>'Sake furay','description'=>'','price'=>4500,'producttype_id'=>2]);
        Product::create(['name'=>'Cali salu (palta)','description'=>'','price'=>5200,'producttype_id'=>3]);
        Product::create(['name'=>'Avocado esp (palta)','description'=>'','price'=>5500,'producttype_id'=>3]);
        Product::create(['name'=>'Spicy tempu (palta)','description'=>'','price'=>5500,'producttype_id'=>3]);
        Product::create(['name'=>'Spicy tako (palta)','description'=>'','price'=>5500,'producttype_id'=>3]);
        Product::create(['name'=>'Beef rolls (palta)','description'=>'','price'=>5500,'producttype_id'=>3]);
        Product::create(['name'=>'Maguro rolls (palta)','description'=>'','price'=>5500,'producttype_id'=>3]);
        Product::create(['name'=>'Temp chees (palta)','description'=>'','price'=>5200,'producttype_id'=>3]);
        Product::create(['name'=>'Tory rolls (palta)','description'=>'','price'=>5200,'producttype_id'=>3]);
        Product::create(['name'=>'Maki rolls (palta)','description'=>'','price'=>5000,'producttype_id'=>3]);
        Product::create(['name'=>'Tako rolls (palta)','description'=>'','price'=>5200,'producttype_id'=>3]);
        Product::create(['name'=>'Crab chees (palta)','description'=>'','price'=>5200,'producttype_id'=>3]);
        Product::create(['name'=>'Teri chees (palta)','description'=>'','price'=>5500,'producttype_id'=>3]);
        Product::create(['name'=>'EBI rolls  (palta)','description'=>'','price'=>5000,'producttype_id'=>3]);
        Product::create(['name'=>'Sake furay (palta)','description'=>'','price'=>5200,'producttype_id'=>3]);
        Product::create(['name'=>'Cali salu (masago)','description'=>'','price'=>4500,'producttype_id'=>4]);
        Product::create(['name'=>'Avocado esp (masago)','description'=>'','price'=>4500,'producttype_id'=>4]);
        Product::create(['name'=>'Spicy temp (masago)','description'=>'','price'=>4800,'producttype_id'=>4]);
        Product::create(['name'=>'Spicy tako (masago)','description'=>'','price'=>5000,'producttype_id'=>4]);
        Product::create(['name'=>'Beef rolls (masago)','description'=>'','price'=>5000,'producttype_id'=>4]);
        Product::create(['name'=>'Maguro (masago)','description'=>'','price'=>4500,'producttype_id'=>4]);
        Product::create(['name'=>'Temp chees (masago)','description'=>'','price'=>4500,'producttype_id'=>4]);
        Product::create(['name'=>'Tory rolls (masago)','description'=>'','price'=>4200,'producttype_id'=>4]);
        Product::create(['name'=>'Maki rolls (masago)','description'=>'','price'=>4000,'producttype_id'=>4]);
        Product::create(['name'=>'Tako rolls (masago)','description'=>'','price'=>4500,'producttype_id'=>4]);
        Product::create(['name'=>'Crab chees (masago)','description'=>'','price'=>5000,'producttype_id'=>4]);
        Product::create(['name'=>'Teri chees (masago)','description'=>'','price'=>4000,'producttype_id'=>4]);
        Product::create(['name'=>'EBI rolls (masago)','description'=>'','price'=>4500,'producttype_id'=>4]);
        Product::create(['name'=>'Sake fuary (masago)','description'=>'','price'=>4500,'producttype_id'=>4]);
        Product::create(['name'=>'Cali salu (ciboule)','description'=>'','price'=>4500,'producttype_id'=>5]);
        Product::create(['name'=>'Avocado es (ciboule)','description'=>'','price'=>4500,'producttype_id'=>5]);
        Product::create(['name'=>'Spicy temp (ciboule)','description'=>'','price'=>4800,'producttype_id'=>5]);
        Product::create(['name'=>'Spicy tako (ciboule)','description'=>'','price'=>5000,'producttype_id'=>5]);
        Product::create(['name'=>'Beef rolls (ciboule)','description'=>'','price'=>5000,'producttype_id'=>5]);
        Product::create(['name'=>'Magur (ciboule)','description'=>'','price'=>4500,'producttype_id'=>5]);
        Product::create(['name'=>'Temp chees (ciboule)','description'=>'','price'=>4500,'producttype_id'=>5]);
        Product::create(['name'=>'Tory rolls (ciboule)','description'=>'','price'=>4200,'producttype_id'=>5]);
        Product::create(['name'=>'Maki rolls (ciboule)','description'=>'','price'=>4000,'producttype_id'=>5]);
        Product::create(['name'=>'Taki rolls (ciboule)','description'=>'','price'=>4500,'producttype_id'=>5]);
        Product::create(['name'=>'Crab chees (ciboule)','description'=>'','price'=>5000,'producttype_id'=>5]);
        Product::create(['name'=>'Teri chees (ciboule)','description'=>'','price'=>4000,'producttype_id'=>5]);
        Product::create(['name'=>'EBI rolls (ciboule)','description'=>'','price'=>4500,'producttype_id'=>5]);
        Product::create(['name'=>'Sake furay (ciboule)','description'=>'','price'=>4500,'producttype_id'=>5]);
        Product::create(['name'=>'Calif veg (sesamo)','description'=>'','price'=>4200,'producttype_id'=>6]);
        Product::create(['name'=>'Champ fur (palta)','description'=>'','price'=>4500,'producttype_id'=>6]);
        Product::create(['name'=>'Veg roll (panko)','description'=>'','price'=>4200,'producttype_id'=>6]);
        Product::create(['name'=>'Palmi (env queso)','description'=>'','price'=>4500,'producttype_id'=>6]);
        Product::create(['name'=>'Veggie (panko)','description'=>'','price'=>4500,'producttype_id'=>6]);
        Product::create(['name'=>'Pollo apa (Q crema)','description'=>'','price'=>5000,'producttype_id'=>7]);
        Product::create(['name'=>'Cama/pal (Q crema)','description'=>'','price'=>5000,'producttype_id'=>7]);
        Product::create(['name'=>'Sal/pal (Q crema)','description'=>'','price'=>5200,'producttype_id'=>7]);
        Product::create(['name'=>'Pul/Pal (Q crema)','description'=>'','price'=>5500,'producttype_id'=>7]);
        Product::create(['name'=>'Cam tem (Q crema)','description'=>'','price'=>5500,'producttype_id'=>7]);
        Product::create(['name'=>'Cam/sal (Q crema)','description'=>'','price'=>5500,'producttype_id'=>7]);
        Product::create(['name'=>'Carn/pal (Q crema)','description'=>'','price'=>5000,'producttype_id'=>7]);
        Product::create(['name'=>'Kani/pal (Q crema)','description'=>'','price'=>4800,'producttype_id'=>7]);
        Product::create(['name'=>'Hot roll (Panko)','description'=>'','price'=>5500,'producttype_id'=>8]);
        Product::create(['name'=>'Tempu sake (Panko)','description'=>'','price'=>5500,'producttype_id'=>8]);
        Product::create(['name'=>'Tempu tako (Panko)','description'=>'','price'=>5300,'producttype_id'=>8]);
        Product::create(['name'=>'Tory furai (Panko)','description'=>'','price'=>5500,'producttype_id'=>8]);
        Product::create(['name'=>'Tempu tery (Panko)','description'=>'','price'=>5500,'producttype_id'=>8]);
        Product::create(['name'=>'Tempura ESP (Panko)','description'=>'','price'=>5500,'producttype_id'=>8]);
        Product::create(['name'=>'Crab roll (Panko)','description'=>'','price'=>5000,'producttype_id'=>8]);
        Product::create(['name'=>'Avocado temp (Panko)','description'=>'','price'=>5500,'producttype_id'=>8]);
        Product::create(['name'=>'Tory teri (Panko)','description'=>'','price'=>5000,'producttype_id'=>8]);
        Product::create(['name'=>'Beef furay (Panko)','description'=>'','price'=>5300,'producttype_id'=>8]);
        Product::create(['name'=>'Maki hot (Panko)','description'=>'','price'=>5000,'producttype_id'=>8]);
        Product::create(['name'=>'Guacamole rolls','description'=>'','price'=>5800,'producttype_id'=>8]);
        Product::create(['name'=>'Cali salu (Salmon)','description'=>'','price'=>5200,'producttype_id'=>9]);
        Product::create(['name'=>'Avocado ESP (Salmon)','description'=>'','price'=>5500,'producttype_id'=>9]);
        Product::create(['name'=>'Spicy temp (Salmon)','description'=>'','price'=>5500,'producttype_id'=>9]);
        Product::create(['name'=>'Spicy tako (Salmon)','description'=>'','price'=>5500,'producttype_id'=>9]);
        Product::create(['name'=>'Beef roll (Salmon)','description'=>'','price'=>5500,'producttype_id'=>9]);
        Product::create(['name'=>'Maguro roll (Salmon)','description'=>'','price'=>5500,'producttype_id'=>9]);
        Product::create(['name'=>'Temp chees (Salmon)','description'=>'','price'=>5200,'producttype_id'=>9]);
        Product::create(['name'=>'Tory roll (Salmon)','description'=>'','price'=>5200,'producttype_id'=>9]);
        Product::create(['name'=>'Maki roll (Salmon)','description'=>'','price'=>5000,'producttype_id'=>9]);
        Product::create(['name'=>'Tako roll (Salmon)','description'=>'','price'=>5200,'producttype_id'=>9]);
        Product::create(['name'=>'Crab chees (Salmon)','description'=>'','price'=>5500,'producttype_id'=>9]);
        Product::create(['name'=>'Teri chees (Salmon)','description'=>'','price'=>5500,'producttype_id'=>9]);
        Product::create(['name'=>'EBI roll (Salmon)','description'=>'','price'=>5000,'producttype_id'=>9]);
        Product::create(['name'=>'Sake furay (Salmon)','description'=>'','price'=>5200,'producttype_id'=>9]);
        Product::create(['name'=>'Gohan cama apana','description'=>'','price'=>6500,'producttype_id'=>10]);
        Product::create(['name'=>'Gohan camaron','description'=>'','price'=>6000,'producttype_id'=>10]);
        Product::create(['name'=>'Gohan carne','description'=>'','price'=>6000,'producttype_id'=>10]);
        Product::create(['name'=>'Gohan de atun','description'=>'','price'=>8500,'producttype_id'=>10]);
        Product::create(['name'=>'Gohan de lomo salteado','description'=>'','price'=>7200,'producttype_id'=>10]);
        Product::create(['name'=>'Gohan kanikama','description'=>'','price'=>5500,'producttype_id'=>10]);
        Product::create(['name'=>'Gohan mixto','description'=>'','price'=>6500,'producttype_id'=>10]);
        Product::create(['name'=>'Gohan pollo','description'=>'','price'=>5800,'producttype_id'=>10]);
        Product::create(['name'=>'Gohan pollo apanado','description'=>'','price'=>6500,'producttype_id'=>10]);
        Product::create(['name'=>'Gohan salmon','description'=>'','price'=>7000,'producttype_id'=>10]);
        Product::create(['name'=>'Gohan vegetariano','description'=>'','price'=>5500,'producttype_id'=>10]);
        Product::create(['name'=>'Acevichada','description'=>'','price'=>1200,'producttype_id'=>11]);
        Product::create(['name'=>'Agridulce extra','description'=>'','price'=>800,'producttype_id'=>11]);
        Product::create(['name'=>'Ceviche','description'=>'','price'=>5000,'producttype_id'=>11]);
        Product::create(['name'=>'Huancaina','description'=>'','price'=>1200,'producttype_id'=>11]);
        Product::create(['name'=>'Maracuya','description'=>'','price'=>1200,'producttype_id'=>11]);
        Product::create(['name'=>'Olivo','description'=>'','price'=>1200,'producttype_id'=>11]);
        Product::create(['name'=>'Palitos extras','description'=>'','price'=>150,'producttype_id'=>11]);
        Product::create(['name'=>'Palos de ayuda','description'=>'','price'=>300,'producttype_id'=>11]);
        Product::create(['name'=>'Salsa spicy','description'=>'','price'=>1000,'producttype_id'=>11]);
        Product::create(['name'=>'Soya extra','description'=>'','price'=>500,'producttype_id'=>11]);
        Product::create(['name'=>'Agua con gas','description'=>'','price'=>1000,'producttype_id'=>12]);
        Product::create(['name'=>'Agua sin gas','description'=>'','price'=>1000,'producttype_id'=>12]);
        Product::create(['name'=>'Bebida coca','description'=>'','price'=>2500,'producttype_id'=>12]);
        Product::create(['name'=>'Bebida coca zero','description'=>'','price'=>2100,'producttype_id'=>12]);
        Product::create(['name'=>'Bebida fanta','description'=>'','price'=>2100,'producttype_id'=>12]);
        Product::create(['name'=>'Bebida sprite','description'=>'','price'=>2100,'producttype_id'=>12]);
        Product::create(['name'=>'Cerveza','description'=>'','price'=>2800,'producttype_id'=>12]);
        Product::create(['name'=>'Coca lata','description'=>'','price'=>1000,'producttype_id'=>12]);
        Product::create(['name'=>'Coca zero lata','description'=>'','price'=>1000,'producttype_id'=>12]);
        Product::create(['name'=>'Energeticas','description'=>'','price'=>2200,'producttype_id'=>12]);
        Product::create(['name'=>'Fanta lata','description'=>'','price'=>1000,'producttype_id'=>12]);
        Product::create(['name'=>'Jugo natural','description'=>'','price'=>2900,'producttype_id'=>12]);
        Product::create(['name'=>'Limonada','description'=>'','price'=>1500,'producttype_id'=>12]);
        Product::create(['name'=>'Michelada','description'=>'','price'=>500,'producttype_id'=>12]);
        Product::create(['name'=>'Sprite lata','description'=>'','price'=>1000,'producttype_id'=>12]);
        Product::create(['name'=>'Te','description'=>'','price'=>1000,'producttype_id'=>12]);
        Product::create(['name'=>'Brownie','description'=>'','price'=>4200,'producttype_id'=>13]);
        Product::create(['name'=>'Cheese Oreo','description'=>'','price'=>4200,'producttype_id'=>13]);
        Product::create(['name'=>'Cheese trilogia','description'=>'','price'=>4200,'producttype_id'=>13]);
        Product::create(['name'=>'Maracuya','description'=>'','price'=>4200,'producttype_id'=>13]);
        Product::create(['name'=>'Pie de limon','description'=>'','price'=>4200,'producttype_id'=>13]);
        Product::create(['name'=>'Envuelto en pulpo','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Ace ebi (Salmon)','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Ace ebi (Palta)','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Env. en mango','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Sake tartare','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Sin arroz en palta','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Sin arroz frito','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Sin arroz en salmon','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Sin arroz c/p frito','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Sin arroz en queso','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Ceviche rolls','description'=>'','price'=>7000,'producttype_id'=>14]);
        Product::create(['name'=>'Lomo saltado','description'=>'','price'=>7000,'producttype_id'=>14]);
        Product::create(['name'=>'Pil pil','description'=>'','price'=>7000,'producttype_id'=>14]);
        Product::create(['name'=>'Tuna sin arroz','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Rolls envuelto en atun','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Rolls al olivo','description'=>'','price'=>7000,'producttype_id'=>14]);
        Product::create(['name'=>'Rolls a la huancaina','description'=>'','price'=>7000,'producttype_id'=>14]);
        Product::create(['name'=>'Rolls delixius olivo','description'=>'','price'=>7000,'producttype_id'=>14]);
        Product::create(['name'=>'Rolls flameados','description'=>'','price'=>7500,'producttype_id'=>14]);
        Product::create(['name'=>'Oriental acevichado','description'=>'','price'=>6500,'producttype_id'=>14]);
        Product::create(['name'=>'Rolls con pulpo','description'=>'','price'=>8500,'producttype_id'=>14]);
        Product::create(['name'=>'Rolls de arroz en atun','description'=>'','price'=>7000,'producttype_id'=>14]);
        Product::create(['name'=>'Promo 15 piezas','description'=>'','price'=>7000,'producttype_id'=>15]);
        Product::create(['name'=>'Promo 20 fritas','description'=>'','price'=>8000,'producttype_id'=>15]);
        Product::create(['name'=>'Promo 30 mixtas','description'=>'','price'=>12000,'producttype_id'=>15]);
        Product::create(['name'=>'Promo 40 mixtas','description'=>'','price'=>14600,'producttype_id'=>15]);
        Product::create(['name'=>'Promo 40 fritas','description'=>'','price'=>15000,'producttype_id'=>15]);
        Product::create(['name'=>'Promo 50 vip','description'=>'','price'=>18500,'producttype_id'=>15]);
        Product::create(['name'=>'Promo 60 mixtas','description'=>'','price'=>19000,'producttype_id'=>15]);
        Product::create(['name'=>'Promo 20 y 20 pollo','description'=>'','price'=>13900,'producttype_id'=>15]);
        Product::create(['name'=>'Promo 40 fritas pollo','description'=>'','price'=>13000,'producttype_id'=>15]);
        Product::create(['name'=>'Promo 3 hand rolls','description'=>'','price'=>9000,'producttype_id'=>15]);
        Product::create(['name'=>'40 pollo promocion frita','description'=>'','price'=>10000,'producttype_id'=>15]);
        Product::create(['name'=>'Promo 2 hand rolls','description'=>'','price'=>6500,'producttype_id'=>15]);
        Product::create(['name'=>'Promo 30 fritas','description'=>'','price'=>10000,'producttype_id'=>15]);
        Product::create(['name'=>'Promo vegetariana 40 piezas','description'=>'','price'=>11500,'producttype_id'=>15]);
        Product::create(['name'=>'California salumado','description'=>'','price'=>7000,'producttype_id'=>16]);
        Product::create(['name'=>'Hot rolls','description'=>'','price'=>5600,'producttype_id'=>16]);
        Product::create(['name'=>'Tempura tako','description'=>'','price'=>6700,'producttype_id'=>16]);
        Product::create(['name'=>'Tempura tery rolls','description'=>'','price'=>6500,'producttype_id'=>16]);
        Product::create(['name'=>'Tempura cheese','description'=>'','price'=>7000,'producttype_id'=>16]);
        Product::create(['name'=>'Tempura especial','description'=>'','price'=>7400,'producttype_id'=>16]);
        Product::create(['name'=>'Tempura especial','description'=>'','price'=>6900,'producttype_id'=>16]);
        Product::create(['name'=>'Avocado tempura','description'=>'','price'=>7000,'producttype_id'=>16]);
        Product::create(['name'=>'En queso crema','description'=>'','price'=>5000,'producttype_id'=>16]);
        Product::create(['name'=>'Tory rolls','description'=>'','price'=>5800,'producttype_id'=>16]);
        Product::create(['name'=>'Cheese rolls','description'=>'','price'=>5300,'producttype_id'=>16]);
        Product::create(['name'=>'Chesse rolls','description'=>'','price'=>5400,'producttype_id'=>16]);
        Product::create(['name'=>'Vege rolls','description'=>'','price'=>5500,'producttype_id'=>16]);
        Product::create(['name'=>'Maki rolls palta','description'=>'','price'=>5700,'producttype_id'=>16]);
        Product::create(['name'=>'Acevichado palta','description'=>'','price'=>6100,'producttype_id'=>16]);
        Product::create(['name'=>'Sin arroz frito ','description'=>'','price'=>6400,'producttype_id'=>16]);
        Product::create(['name'=>'Sin arroz','description'=>'','price'=>6400,'producttype_id'=>16]);
        Product::create(['name'=>'Ceviche rolls','description'=>'','price'=>7500,'producttype_id'=>16]);
        Product::create(['name'=>'Acevichado EBI','description'=>'','price'=>7100,'producttype_id'=>16]);
        Product::create(['name'=>'California vegetariano','description'=>'','price'=>5500,'producttype_id'=>16]);
        Product::create(['name'=>'Camaron apanados','description'=>'','price'=>6000,'producttype_id'=>16]);
        Product::create(['name'=>'Camarones queso','description'=>'','price'=>6500,'producttype_id'=>16]);
        Product::create(['name'=>'Champy furay','description'=>'','price'=>5600,'producttype_id'=>16]);
        Product::create(['name'=>'Cheesecake mango','description'=>'','price'=>5000,'producttype_id'=>16]);
        Product::create(['name'=>'Env salm(camar o salm)','description'=>'','price'=>7100,'producttype_id'=>16]);
        Product::create(['name'=>'Fanta','description'=>'','price'=>1200,'producttype_id'=>16]);
        Product::create(['name'=>'Gohan camaron','description'=>'','price'=>7400,'producttype_id'=>16]);
        Product::create(['name'=>'Gohan de kanikama','description'=>'','price'=>6200,'producttype_id'=>16]);
        Product::create(['name'=>'Gohan mixto','description'=>'','price'=>7000,'producttype_id'=>16]);
        Product::create(['name'=>'Gohan salmon','description'=>'','price'=>7600,'producttype_id'=>16]);
        Product::create(['name'=>'Gohan vegetariano','description'=>'','price'=>7200,'producttype_id'=>16]);
        Product::create(['name'=>'Gyosas camaron','description'=>'','price'=>5000,'producttype_id'=>16]);
        Product::create(['name'=>'Gyosas cerdo','description'=>'','price'=>4700,'producttype_id'=>16]);
        Product::create(['name'=>'Gyosas pollo','description'=>'','price'=>4700,'producttype_id'=>16]);
        Product::create(['name'=>'Hot rolls','description'=>'','price'=>6600,'producttype_id'=>16]);
        Product::create(['name'=>'Mango','description'=>'','price'=>7200,'producttype_id'=>16]);
        Product::create(['name'=>'Palmito white','description'=>'','price'=>5800,'producttype_id'=>16]);
        Product::create(['name'=>'Sashimi sake','description'=>'','price'=>4000,'producttype_id'=>16]);
        Product::create(['name'=>'Sashimi tako','description'=>'','price'=>5000,'producttype_id'=>16]);
        Product::create(['name'=>'Spicy temp roll','description'=>'','price'=>7000,'producttype_id'=>16]);
        Product::create(['name'=>'Tory balls','description'=>'','price'=>6200,'producttype_id'=>16]);
        Product::create(['name'=>'Tory rolls','description'=>'','price'=>6800,'producttype_id'=>16]);
        Product::create(['name'=>'Veggie furay','description'=>'','price'=>5800,'producttype_id'=>16]);
        Product::create(['name'=>'2 Micheladas','description'=>'','price'=>5000,'producttype_id'=>17]);
        Product::create(['name'=>'Cerveza grande','description'=>'','price'=>4000,'producttype_id'=>17]);
        Product::create(['name'=>'Michelada','description'=>'','price'=>3500,'producttype_id'=>17]);
        Product::create(['name'=>'Pisco 2 sour','description'=>'','price'=>6000,'producttype_id'=>17]);
        Product::create(['name'=>'Pisco sour','description'=>'','price'=>4500,'producttype_id'=>17]);
        Product::create(['name'=>'Piscola','description'=>'','price'=>3000,'producttype_id'=>17]);
        Product::create(['name'=>'Promo piscola','description'=>'','price'=>5000,'producttype_id'=>17]);
        Product::create(['name'=>'Handroll pollo','description'=>'','price'=>3500,'producttype_id'=>18]);
        Product::create(['name'=>'Handroll camaron','description'=>'','price'=>3900,'producttype_id'=>18]);
        Product::create(['name'=>'Handroll carne','description'=>'','price'=>3500,'producttype_id'=>18]);
        Product::create(['name'=>'Handroll kanikama','description'=>'','price'=>3500,'producttype_id'=>18]);
        Product::create(['name'=>'Handroll salmon','description'=>'','price'=>3900,'producttype_id'=>18]);
        Product::create(['name'=>'Handroll vegetariano','description'=>'','price'=>3500,'producttype_id'=>18]);
        Product::create(['name'=>'otros','description'=>'','price'=>800,'producttype_id'=>19]);
        Product::create(['name'=>'Almendras','description'=>'','price'=>1000,'producttype_id'=>19]);
        Product::create(['name'=>'Camaron normal','description'=>'','price'=>1000,'producttype_id'=>19]);
        Product::create(['name'=>'Camaron apanados','description'=>'','price'=>1200,'producttype_id'=>19]);
        Product::create(['name'=>'Cambio','description'=>'','price'=>1000,'producttype_id'=>19]);
        Product::create(['name'=>'Carne','description'=>'','price'=>1000,'producttype_id'=>19]);
        Product::create(['name'=>'Cebollin','description'=>'','price'=>700,'producttype_id'=>19]);
        Product::create(['name'=>'Ceviche rolls','description'=>'','price'=>2000,'producttype_id'=>19]);
        Product::create(['name'=>'Champiñon','description'=>'','price'=>700,'producttype_id'=>19]);
        Product::create(['name'=>'Choclo enano','description'=>'','price'=>700,'producttype_id'=>19]);
        Product::create(['name'=>'Ciboulette','description'=>'','price'=>700,'producttype_id'=>19]);
        Product::create(['name'=>'Jaiba','description'=>'','price'=>1200,'producttype_id'=>19]);
        Product::create(['name'=>'Kanikama','description'=>'','price'=>1000,'producttype_id'=>19]);
        Product::create(['name'=>'Palmito','description'=>'','price'=>700,'producttype_id'=>19]);
        Product::create(['name'=>'Palta','description'=>'','price'=>700,'producttype_id'=>19]);
        Product::create(['name'=>'Panko','description'=>'','price'=>1000,'producttype_id'=>19]);
        Product::create(['name'=>'Pimenton','description'=>'','price'=>700,'producttype_id'=>19]);
        Product::create(['name'=>'Pollo','description'=>'','price'=>1000,'producttype_id'=>19]);
        Product::create(['name'=>'Pollo apanado','description'=>'','price'=>1200,'producttype_id'=>19]);
        Product::create(['name'=>'Pulpo','description'=>'','price'=>1200,'producttype_id'=>19]);
        Product::create(['name'=>'Queso crema','description'=>'','price'=>1000,'producttype_id'=>19]);
        Product::create(['name'=>'Salmon','description'=>'','price'=>1200,'producttype_id'=>19]);
        Product::create(['name'=>'Salmon ahumado','description'=>'','price'=>1200,'producttype_id'=>19]);
    }
}
